apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  labels:
    app: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        image: gcr.io/project-backup-308223/microservice:ca899b1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
---
kind: Service
apiVersion: v1
metadata:
  name: microservice
spec:
  selector:
    app: microservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer