apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  labels:
    app: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        image: gcr.io/project-backup-308223/microservice:38f65e6
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "150m"
          requests:
            cpu: "100m"
---
kind: Service
apiVersion: v1
metadata:
  name: microservice
spec:
  selector:
    app: microservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: microservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microservice
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 90